import { StoreProvider } from '@/redux/StoreProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import CSThemeProvider from './CSThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
declare global {
  interface Window {
    initMap: () => void;
  }
}
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <CSThemeProvider>
          <body className={inter.className}>{children}</body>
        </CSThemeProvider>
      </StoreProvider>
    </html>
  );
}
